### ISSUE TITLE
Create Scooter Model (M)

### ISSUE THREAD

**Issue by nymphadora-tonks-team** [nymphadora-tonks-team/booking-jb#1]
Scooter : 
- serialNumber: String
- currentLocation: { latitude: Double, longitude: Double }
- batteryLevel: { level: Double, BatteryStatus(ENUM): LOW=[0, 30), MEDIUM=[30,60), HIGH=[60, 100] }
- status - AVAILABLE, RESERVED

**Comment by dbernatt** [comment]
E ok asa? 
- batteryLevel (LOW=[0, 30), MEDIUM=[30,60), HIGH=[60, 100])
